### ISSUE TITLE
Abuse in discord

### ISSUE THREAD

**Issue by NadirAli01** [Bluethefurry/anticheese-anticheat#7]
WTF.? Admin your discord support members is crazy ? i ask him about anticheat and he is abuse and banned me on discord, this is not fair.!

**Comment by sambeano7** [comment]
We didn't abuse or ban you...you are free to join back...just don't ping us

**Comment by NadirAli01** [comment]
you are banned me i know and who abuse you know, i send you screenshot in discord server . only waste users time not any support 
btw i dont waste my time anymore! Bye


![image](https://user-images.githubusercontent.com/65899205/85096680-79255f00-b20e-11ea-80d7-e245204ae1be.png)

**Comment by sambeano7** [comment]
that says kick not ban
https://prnt.sc/t2gzm6
